language: node_js
node_js:
    - 'lts/*'
install:
    - git submodule update --init --recursive
    - yarn install --frozen-lockfile
    - ./setup-submodules.sh
script:
    - npm run test
    - npm run lint
    - npm run build:ci
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
